### ISSUE TITLE
Official guide on how to use it

### ISSUE THREAD

**Issue by Kamar-Meddah** [Cloudslab/iFogSim1#14]
hello , there is no official documentation on how to use ifogsim or a real tutorials on how to use it, i wish if there will be an official guide on how to use and an examples with explanation

**Comment by msschl** [comment]
To get started, I would recommend the paper `iFogSim: A toolkit for modeling and simulation of resource management techniques in the Internet of Things, Edge and Fog computing environments` by Gupta, Dastjerdi, Ghosh and Buyya.

**Comment by Kamar-Meddah** [comment]
I've analyzed the the code on discover how to use it , that paper isn't really clear but it helped me a lot thanks

**Comment by Caro9** [comment]
> I've analyzed the the code on discover how to use it , that paper isn't really clear but it helped me a lot thanks

please Kamar, if you found something to understand how to use ifogsim please help me

**Comment by sandeepkhandare2021** [comment]
How to record output and result into excel or other format?
